# Generated by Django 5.2.1 on 2025-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="area",
            name="features",
            field=models.TextField(blank=True, null=True),
        ),
    ]
