# Generated by Django 5.2.1 on 2025-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_area_description_area_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="category",
            field=models.CharField(
                choices=[
                    ("study", "Study Room"),
                    ("lab", "Lab"),
                    ("classroom", "Classroom"),
                ],
                default="study",
                max_length=20,
            ),
        ),
    ]
