# Generated by Django 5.2.1 on 2025-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("electrical", "Elektrik"),
                            ("furniture", "Mobilya"),
                            ("equipment", "Donanım"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("resolved", models.BooleanField(default=False)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
