# Generated by Django 5.2.1 on 2025-05-11 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="issuereport",
            name="building",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="issuereport",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="issue_images/"),
        ),
        migrations.AddField(
            model_name="issuereport",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Düşük"),
                    ("medium", "Orta"),
                    ("high", "Yüksek"),
                    ("emergency", "Acil"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issuereport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Beklemede"),
                    ("in_progress", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                    ("assigned", "Atandı"),
                ],
                default="pending",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="issuereport",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("electrical", "Elektrik"),
                    ("furniture", "Mobilya"),
                    ("equipment", "Donanım"),
                    ("plumbing", "Tesisat"),
                    ("hvac", "HVAC/Isıtma-Soğutma"),
                    ("structural", "Yapısal"),
                    ("cleaning", "Temizlik"),
                    ("technology", "Teknoloji"),
                    ("other", "Diğer"),
                ],
                max_length=50,
            ),
        ),
    ]
