# Generated by Django 5.2.1 on 2025-05-11 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_issuereport_building_issuereport_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuereport",
            name="building",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Düşük"),
                    ("medium", "Orta"),
                    ("high", "Yüksek"),
                    ("emergency", "Acil"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("in_progress", "Devam Ediyor"),
                    ("completed", "Tamamlandı"),
                    ("assigned", "Atandı"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
