# Generated by Django 5.2.1 on 2025-05-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lost_and_found", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostitem",
            name="category",
            field=models.CharField(default="other", max_length=100),
        ),
    ]
