# Generated by Django 5.2.1 on 2025-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lost_and_found", "0002_lostitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostitem",
            name="contact_info",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lostitem",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="lostitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="lost_items/"),
        ),
    ]
