# Generated by Django 5.2.1 on 2025-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("occupancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                ("current_person_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("occupied", "Occupied")],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
