# Generated by Django 5.2.1 on 2025-05-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationlog",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="areas.area",
            ),
        ),
    ]
