# Generated by Django 5.2.1 on 2025-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
